# Site settings
title: Cloudgate Studios
description: "Simple app development in the Chicago suburbs"
url: "http://www.cloudgatestudios.com"

# Build settings
baseurl: 
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:

# Custom variables
version: "1.0.0"
